name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Enforce Formatting
      run: cargo fmt --check
    - name: Linting
      run: cargo clippy -- -D warnings 
    - name: Generate code coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    - name: Generate report
      run: cargo llvm-cov report --html --output-dir coverage
    - uses: actions/upload-artifact@v4
      with:
        name: "Coverage report"
        path: coverage/
